### ISSUE TITLE
Sample Code Compilation error

### ISSUE THREAD

**Issue by tonydavies57** [m5stack/ATOM_DTU_LoRaWAN#2]
probably a noob question, but when I copied the code LoRaWAN_OTAA.ino in my Arduino IDE, I get this error on compile

'UNIT_LoRaWAN' does not name a type; did you mean 'ATOM_DTU_LoRaWAN'?

I have the libraries ATOM_DTU_LoRaWAN and M5Atom installed (I am using a M5 Atom Lite with the LoRAWAN868 unit.

Any idea what I am doing wrong?

Thanks

**Comment by tonydavies57** [comment]
i used another method to install libraries (Sketch/Include Library/Add .Zip library)  and it now compiles

**Comment by TinyuZhao** [comment]
You are missing the relevant dependencies.
- [UNIT_LoRaWAN](https://github.com/m5stack/UNIT_LoRaWAN)
- [M5Atom](https://github.com/m5stack/M5Atom)
- [FastLED](https://github.com/FastLED/FastLED)
